### ISSUE TITLE
Assets Broken

### ISSUE THREAD

**Issue by mstaack** [digistump/DigistumpArduino#115]
Currently using this board json results in a http 403 on asset download.

```... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 403
	at cc.arduino.utils.network.FileDownloader.openConnectionAndFillTheFile(FileDownloader.java:239)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:182)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:129)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:147)
	... 5 more
 Fehler beim Herunterladen von https://github.com/digistump/DigistumpArduino/releases/download/1.6.7/digistump-avr-1.6.7.zip
java.lang.RuntimeException: java.lang.Exception: Fehler beim Herunterladen von https://github.com/digistump/DigistumpArduino/releases/download/1.6.7/digistump-avr-1.6.7.zip
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:175)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ArminJo** [comment]
Try [this](https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json) one and you will be happy :grin:
