### ISSUE TITLE
NOt able to manage Arduino Dude board

### ISSUE THREAD

**Issue by rameshad** [digistump/DigistumpArduino#82]
Having issues managing Arduino Dude Board, getting following error
 Error downloading http://downloads.arduino.cc/packages/package_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$1(ContributionManagerUI.java:150)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:139)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:333)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:307)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:285)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$1(ContributionManagerUI.java:146)
	... 1 more
Caused by: java.nio.file.FileSystemException: C:\Users\TVSAUTOMATION\AppData\Local\Arduino15\package_index.json.tmp: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:156)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:132)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:137)
	... 5 more
Index error: could not find referenced tool name=avr-gcc version=4.8.1-arduino5 packager=arduino
Index error: could not find referenced tool name=avrdude version=6.0.1-arduino5 packager=arduino
Index error: could not find referenced tool name=avr-gcc version=4.8.1-arduino5 packager=arduino
Index error: could not find referenced tool name=avrdude version=6.0.1-arduino5 packager=arduino
Index error: could not find referenced tool name=avr-gcc version=4.8.1-arduino5 packager=arduino

**Comment by bratoff** [comment]
Do you mean Arduino Due?  If yes, you're in the wrong repository.  

Try your question in the Arduino/arduino repository.

**Comment by ArminJo** [comment]
@rameshad Could you please be so kind and close this Issue?
Thanks
Armin
